name: CommunicateHealth Dev Blog
description: CommunicateHealth Dev Blog
baseurl: ""
url: "https://communicatehealth.github.io" # the base hostname & protocol for your site

port: 4000
host: 127.0.0.1

sass:
  sass_dir: _scss
  style: :compressed

lsi: false
markdown: kramdown
source: .
destination: _site
permalink: /:categories/:title/
timezone: America/New_York

feed:
  path: feed.xml

exclude: [node_modules, '.sass-cache', Gemfile, Gemfile.lock, README.md, package.json, Gruntfile.js]

collections:
  content:
    output: true
